### ISSUE TITLE
Feature Request: Have "Refresh Segmentation" also refresh TODOs and bookmarks

### ISSUE THREAD

**Issue by pgunn** [janelia-flyem/NeuTu#330]
Right now if the DVID backing NeuTu gets new user bookmarks or todos, the main Neutu window must be closed and reopened to notice them (although other viewers like the orthogonal viewer see changes to TODOs right away). This feature request is for the "Refresh Segmentation" button to change to just "Refresh" and have it re-sync user bookmarks and TODOs from the server.

**Comment by pgunn** [comment]
(refreshing synapses in-view would also be nice)

**Comment by tingzhao** [comment]
I added a new "Refresh Data" item in the context menu for this feature. It's now available in neutu-develop-0.1.post2176. Note that the channel configuration required for this latest version is '-c flyem-forge -c conda-forge'. It is also recommended to install it in a new env instead of updating neutu from an old one because of major updates of conda forge dependencies.

**Comment by pgunn** [comment]
This is great! I'll give it a go later today.
