### ISSUE TITLE
Display server status in neu3

### ISSUE THREAD

**Issue by knechtc** [janelia-flyem/NeuTu#64]
Currently when the cleave server is down the users are still able to place seeds that don't seem to propagate. A server status could allow them to pause work until the issue is resolved.

**Comment by hubbardp** [comment]
With the code in the "neu3-body-cleave-error-handling" branch, if the cleaving server does not respond when the user sets a seed, Neu3 will pop up a dialog that says, "Cleave server error: Connection refused," and the user will have to click an "OK" button before doing anything else.  Chris says that functionality is a pretty good solution to his request.

For the future, it might also be nice for Neu3 to poll the cleave server regularly (say, every 10 seconds), and update an indicator in the user interface so that a user would not have to try to place a seed in order to know that the server had started responding again.

**Comment by hubbardp** [comment]
The "neu3-body-cleave-error-handling" branch is waiting to be merged into the "develop" branch:
https://github.com/janelia-flyem/NeuTu/pull/71

**Comment by hubbardp** [comment]
Merged.
